easy_admin:
    formats:
        datetime: 'd/m/Y H:i:s'
    edit:
        title: 'Modification %%entity_name%%'
    entities:
        # Définition des entitées

        Contact:
            class: App\Entity\Contact
            # Mise en page de la page création d'un contact :
            form:
                fields:
                    - { type: 'section', label: 'Contact : ', icon: 'user' }
                    - { property: 'societe', label: 'Société' }
                    - { property: 'nomContact', label: 'Nom' }
                    - { property: 'prenomContact', label: 'Prenom' }
                    - { type: 'section', label: 'Informations : ', icon: 'phone',
                       css_class: 'danger' }
                    - { property: 'email', type: 'email' }
                    - 'telephone'
                    - { type: 'section', label: 'Adresse : ', icon: 'envelope-o',
                       css_class: 'danger' }
                    - 'adresse'
                    - 'ville'
                    - { type: 'section', label: 'Informations complémentaires : ', icon: 'information',
                       css_class: 'danger' }
                    - { property: 'createdAt', label: 'Date création' }
                    - { property: 'updatedAt', label: 'Date modification' }
                    - 'commentaire'
            #Déclaration des attributs à afficher sur la page Contact :
            list:
                fields: ['societe','nomContact', 'prenomContact', { property: 'email', type: 'email' }, { property: 'telephone', type: 'tel' },
                 'adresse', { property: 'createdAt', label: 'Date création' }, { property: 'updatedAt', label: 'Date modification' },'commentaire']

        Societe:
           class: App\Entity\Societe
           list:
               fields: ['nomSociete', 'siretSociete']
#         Mis en commentaire du menu commentaire :
        Ville:
            class: App\Entity\Ville
            list:
                fields: ['cp', 'ville']

#        Commentaire:
#            class: App\Entity\Commentaire
#            list:
#                fields: ['commentaire']
    #Changement du nom du backend :
    site_name: '<em style="font-size: 80%;"> Fabian </em><a style="font-size: 200% ; color: white;" href="/">Page Accueil </a>'

    #Personnalisation du design :
    design:
            brand_color: '#1ABC9C'
            #color_scheme: 'light'
            #...