easy_admin:
    formats:
        datetime: 'd/m/Y H:i:s'
    edit:
        title: 'Modification %%entity_name%%'
    entities:
        # Définition des entitées
        Societe:
            class: App\Entity\Societe
            list:
                fields: ['nomSociete', 'siretSociete']
        Contact:
            class: App\Entity\Contact
            list:
                fields: ['nomContact', 'prenomContact', { property: 'email', type: 'email' }, { property: 'telephone', type: 'tel' },
                 'adresse', { property: 'createdAt', label: 'Date création' }, { property: 'updatedAt', label: 'Date modification' }]
        Ville:
            class: App\Entity\Ville
            list:
                fields: ['cp', 'ville', 'pays']
        Commentaire:
            class: App\Entity\Commentaire
            list:
                fields: ['commentaire']
    #Changement du nom du backend :
    site_name: 'Fabian <em style="font-size: 80%;"</em>'
    #Personnalisation du design :
    design:
            brand_color: '#1ABC9C'
            #color_scheme: 'light'