easy_admin:
    formats:
        datetime: 'd/m/Y H:i:s'
    edit:
        title: 'Modification %%entity_name%%'
    entities:
        # Définition des entitées
#Affichage des champs de la table User pour la liste et le formulaire
        User:
            class: App\Entity\User
            form:
                fields:
                    - name
                    - email
                    - enabled
                    - lastLogin
                    # if administrators are allowed to edit users' passwords and roles, add this:
                    - { property: 'plainPassword', type: 'text', type_options: { required: false } }
                    - { property: 'roles', type: 'choice', type_options: { multiple: true, choices: { 'ROLE_USER': 'ROLE_USER', 'ROLE_ADMIN': 'ROLE_ADMIN' } } }

            edit:
                fields:
                    # ...
                    - { property: 'plainPassword', type_options: { required: false} }
                    # ...
                form_options: { validation_groups: ['Profile'] }
            new:
                fields:
                    # ...
                    - { property: 'plainPassword', type_options: { required: true} }
                    # ...
                form_options: { validation_groups: ['Registration'] }

#Affichage des champs de la table Contact pour la liste et le formulaire
        Contact:
            class: App\Entity\Contact
            # Mise en page de la page création d'un contact :
            form:
                fields:
                    - { type: 'section', label: 'Contact : ', icon: 'user' }
                    - { property: 'societe', label: 'Société' }
                    - { property: 'nomContact', label: 'Nom' }
                    - { property: 'prenomContact', label: 'Prenom' }
                    - { type: 'section', label: 'Informations : ', icon: 'phone',
                       css_class: 'danger' }
                    - { property: 'email', type: 'email' }
                    - 'telephone'
                    - { type: 'section', label: 'Adresse : ', icon: 'envelope-o',
                       css_class: 'danger' }
                    - 'adresse'
                    - 'ville'
                    - { type: 'section', label: 'Informations complémentaires : ', icon: 'information',
                       css_class: 'danger' }
                    - { property: 'createdAt', label: 'Date création' }
                    - { property: 'updatedAt', label: 'Date modification' }
                    - 'commentaire'
            #Déclaration des attributs à afficher sur la page Contact :
            list:
                fields: ['societe','nomContact', 'prenomContact', { property: 'email', type: 'email' }, { property: 'telephone', type: 'tel' },
                 'adresse', { property: 'createdAt', label: 'Date création' }, { property: 'updatedAt', label: 'Date modification' },'commentaire']

#Affichage des champs de la table Societe pour la liste et le formulaire
        Societe:
            class: App\Entity\Societe
            list:
                fields: ['nomSociete', 'siretSociete']

#Affichage des champs de la table Ville pour la liste et le formulaire
        Ville:
            class: App\Entity\Ville
            list:
                fields: ['cp', 'ville']
#Affichage des champs de la table Projet pour la liste et le formulaire
        Projet:
            class: App\Entity\Projet
            form:
                fields:
                    - { property: 'societe', label: 'Société' }
                    - { property: 'nomProjet', label: 'Nom du projet' }
#                    - { property: 'temps', label: 'Temps' }
#                    - { property: 'fichier', label: 'Fichier' }
            list:
                fields: ['societe','nomProjet']

#Affichage des champs de la table Information pour la liste et le formulaire
        Information:
            class: App\Entity\Information
            form:
                fields:
                    - { property: 'projet', label: 'Projet' }
                    - { property: 'information', label: 'Information' }
            list:
                fields:
                    - { property: 'projet', label: 'Projet' }
                    - { property: 'information', label: 'Information' }
#Affichage des champs de la table Temps pour la liste et le formulaire

        Temps:
            class: App\Entity\Temps
            list:
                fields: ['societe','temps']
#Affichage des champs de la table Fichier pour la liste et le formulaire
        Fichier:
            class: App\Entity\Fichier
            form:
                fields:
                    - { property: 'projet', label: 'Projet' }
                    - { property: 'nomFichier', label: 'Nom du fichier' }
#                    - { property: 'fichier', template: 'fichier.html.twig' }
                    - { property: 'fichierFile', type: 'vich_file' }

            list:
                fields:
                    - { property: 'projet', label: 'Projet' }
                    - { property: 'nomFichier', label: 'Nom du fichier' }
                    - { property: 'fichier', label: 'Fichier', template: 'fichier.html.twig', base_path: '%app.path.projet_fichiers%' }



#         Mis en commentaire du menu commentaire :
#        Commentaire:
#            class: App\Entity\Commentaire
#            list:
#                fields: ['commentaire']
    #Changement du nom du backend :
    site_name: '<em style="font-size: 80%;"> Fabian </em><a style="font-size: 200% ; color: white;" href="/">Page Accueil </a>'

    #Personnalisation du design :
    design:
        brand_color: '#1ABC9C'
        #color_scheme: 'light'
        #...
#        form_theme: ['horizontal', 'VichUploaderBundle:Form:fields.html.twig']