#Création de la route pour la page d'accueil via le AppController
index:
    path: /
    defaults: {_controller: 'App\Controller\AppController::accueil'}

fos_user:
    resource: "@FOSUserBundle/Resources/config/routing/all.xml"
